project:
  type: website
  output-dir: _site

website:
  title: "fyradur"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/fyradur
      - icon: linkedin
        href: https://linkedin.com/in/johnpemoller/

format:
  html:
    theme: cosmo
    css: styles.css



