project:
  type: website
  output-dir: docs

website:
  title: "fyradur"
  navbar:
    right:
      - text: "Posts"
        href: "index.qmd"
      - text: "About"
        href: "about.qmd"
      - icon: github
        href: https://github.com/fyradur
      - icon: linkedin
        href: https://linkedin.com/in/johnpemoller/

format:
  html:
    theme: cosmo
    css: styles.css



